kind: pipeline
name : xKernel Compiler
version: rev1.5_template
steps:
 - name: Build
   image: xyzuan/xdocker:latest
   environment:
     KERNEL_NAME:
       from_secret: KERNEL_NAME
     KERNEL_SOURCE:
       from_secret: KERNEL_SOURCE
     KERNEL_BRANCH:
       from_secret: KERNEL_BRANCH
     DEVICE_CODENAME:
       from_secret: DEVICE_CODENAME
     DEVICE_DEFCONFIG:
       from_secret: DEVICE_DEFCONFIG
     ANYKERNEL:
       from_secret: ANYKERNEL
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     BUILD_USER:
       from_secret: BUILD_USER
     BUILD_HOST:
       from_secret: BUILD_HOST
     GH_USERNAME:
       from_secret: GH_USERNAME
     GH_EMAIL:
       from_secret: GH_EMAIL
     GH_TOKEN:
       from_secret: GH_TOKEN
   commands:
     - bash download.sh
     - bash gcc.sh
     - bash rm.sh
     - bash clang.sh
